name: GPT PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Pythonバージョンを指定

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run GPT PR
      run: python src/main.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
